name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cargo install \
            --git https://github.com/kateinoigakukun/wasminspect.git \
            --features remote-api \
            --root ${{ github.workspace }}
          npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          WASMINSPECT_SERVER_PATH: ${{ github.workspace }}/bin/wasminspect-server

