name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

